version: '2'
services:
    jdl-app:
        image: jdl
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jdl-mysql:3306/jdl?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jdl-mysql:
        extends:
            file: mysql.yml
            service: jdl-mysql
